name: Remote Config

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/config.yml'
      - 'config/**'
      - 'scripts/*'
      - 'scripts/config.sh'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/config.yml'
      - 'config/**'
      - 'scripts/*'
      - 'scripts/config.sh'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd config
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          ../scripts/install_prereqs/config.sh
        env:
          SAMPLE: Config
          secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}
      - name: Build Swift
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ''
          SAMPLE: Config
      - name: Build Catalyst
        run: |
          cd config
          ../scripts/install_prereqs/config.sh
          pod install
          xcodebuild \
          -configuration Debug \
          -workspace ConfigExample.xcworkspace \
          -scheme ConfigExample \
          -sdk macosx \
          ARCHS=x86_64 VALID_ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO \
          SUPPORTS_MACCATALYST=YES SUPPORTS_UIKITFORMAC=YES \
          CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
          build \
          | xcpretty
        env:
          SAMPLE: Config
          secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}
